config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :instagram, only: [:index, :show, :update]
  resources :tinder, only: [:index, :show, :update]
  resources :local, only: [:index, :show, :update]
  resources :attr_changes
  resources :googlemaps, only: [:index, :show, :update]
  resources :scoreboard, only: [:index, :new, :create]

  resources :events do
  resources :results

  end

  root to: 'welcome#index'

  resources :welcome, only: [:index, :show]
    get '/welcome/fomo_details', to: 'welcome#show'
    resources :game_end, only: [:index]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    gon.gametext = "Your mission, should you choose to accept it:\nA hip, new, trendy bar has just opened in the\nMarina District All ride-sharing services are\nnonexistent. You have to make it to this party\nbefore your FOMO decreases and you literally\ncan't even. Traveling by foot, you have two\nhours to make it to the Marina. You are about\nto witness the struggle of the modern\nmillenial.\n\nThe struggle is real."
  end

  def show
    gon.gametext = "noun, informal\n\nAnxiety that an exciting or interesting event\nmay currently be happening elsewhere, often\naroused by posts seen on social media.\n‘Constant real-time awareness - through\nFacebook check-ins and Twitter updates - of\nthe fun everyone is having can spark the\ninstant insecurity of FOMO, or fear of missing\nout.’"
  end

end

app/views/welcome/index.html.erb
<div class="page-flexbox-wrapper">
  <div id="event-header">
    <h1>Mission Trail</h1>
    <br>
  </div>
    <div id="top-content-buffer"></div>
      <div class="welcome-container">
        <p>Your mission, should you choose to accept it: <br>
        <p>A hip, new, trendy bar has just opened in the Marina District. Due to ethical concerns, all ride-sharing services have been banned. You have to make it to this party before your FOMO increases and you literally can't even.</p> 
        <p> Traveling by foot, you have one hour to make it to the Marina. You are about to witness the struggle of the modern Millenial... </p>
        <p>The struggle is real.</p>
      </div>
    <br>
    <br>
    <%= audio_tag("INTRO.mp3", autoplay: true) %>
    <div class="all-options">
      <div class="options">
        <%= link_to "Start Game", { :action => "show"}, :method => :get %>
        <br>
         <%= link_to "Leaderboard", scoreboard_index_path%>
      </div>
    </div>
</div>

app/views/welcome/show.html.erb
<div class="page-flexbox-wrapper">
  <div id="event-header">
    <h1>What is FOMO?</h1>
  </div>
  <div id="top-content-buffer"></div>
    <div class="welcome-container">
      <p>noun, informal</p>
      <br>
      <p>Anxiety that an exciting or interesting event may currently be happening elsewhere, often aroused by posts seen on social media. </p>
      <p>Example: ‘Constant real-time awareness - through Facebook check-ins and Twitter updates - of the fun everyone is having can spark the instant insecurity of FOMO, or fear of missing out.’</p>
      <p> - Oxford English Dictionary </p>
      <p> Keep Your FOMO Low! </p>
    </div>
        <%= audio_tag("FOMO.mp3", autoplay: true) %>
    <div class="all-options">
      <div class="options">
        <%= link_to "Hop On The Trail", controller: 'games', action: 'new' %>
      </div>
    </div>
</div>