config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :instagram, only: [:index, :show, :update]
  resources :tinder, only: [:index, :show, :update]
  resources :local, only: [:index, :show, :update]
  resources :attr_changes
  resources :googlemaps, only: [:index, :show, :update]
  resources :scoreboard, only: [:index, :new, :create]

  resources :events do
  resources :results

  end

  root to: 'welcome#index'

  resources :welcome, only: [:index, :show]
    get '/welcome/fomo_details', to: 'welcome#show'
    resources :game_end, only: [:index]
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :option
  belongs_to :event
  belongs_to :attr_change

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
  end

  def show
    @event = Event.find(params[:event_id])
    @game = Game.find(session[:id])
    @result = Result.find(params[:id])

    gon.username = @game.username
    gon.gametext = @result.text
    gon.fomo = @game.fomo
    gon.battery = @game.battery
    gon.time = @game.time
    gon.money = @game.money
    gon.gameimage = @result.image_url
  end

  def update
    @game = Game.find(session[:id])
    @result = Result.find(params[:id])
    p @result.attr_change.fomo_change

    p @game.fomo

    @game.update_attributes(fomo: (@game.fomo += @result.attr_change.fomo_change))
    @game.update_attributes(battery: (@game.battery += @result.attr_change.battery_change))
    @game.update_attributes(time: (@game.time += @result.attr_change.time_change))
    @game.update_attributes(money: (@game.money += @result.attr_change.money_change))
    @game.update_attributes(checked_instagram: false)
    @game.update_attributes(checked_tinder: false)
    @game.update_attributes(talked_to_locals: false)
    @game.update_attributes(checked_googlemaps: false)


    redirect_to games_path
  end


end

app/views/results/show.html.erb
<div class="event-flexbox-wrapper">
  <div class="top-content">
    <div id="stats">
      <p> Name: <%= @game.username %> </p>
      <p> FOMO: <%= @game.fomo %>% <br> </p>
      <p> Time: <%= @game.time %> Minutes <br> </p>
      <p> Money: $<%= @game.money %> <br> </p>
      <p> Battery: <%= @game.battery %>% <br> </p>
    </div>
    <div id="event-header">
      <h1>Your Result</h1>
    </div>
    <div id="top-content-buffer"></div>
  </div>
</div>
<div class="options">
  <%=@result.text%>
</div>
<div class="flexbox-event-content">
  <div class="image">
    <img src=<%=@result.image_url%>>
  </div>
  <div id="event-content-buffer"></div>
      <div class="trail-return-link">
        <%= link_to "Return to Trail", event_result_path(@result), method: "put"%>
    </div>
  </div>
</div>