config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :instagram, only: [:index, :show, :update]
  resources :tinder, only: [:index, :show, :update]
  resources :local, only: [:index, :show, :update]
  resources :attr_changes
  resources :googlemaps, only: [:index, :show, :update]
  resources :scoreboard, only: [:index, :new, :create]

  resources :events do
  resources :results

  end

  root to: 'welcome#index'

  resources :welcome, only: [:index, :show]
    get '/welcome/fomo_details', to: 'welcome#show'
    resources :game_end, only: [:index]
end

app/models/game.rb
class Game < ApplicationRecord
  validates :username, :occupation, presence: true

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ApplicationHelper

  def index
    @game = Game.find(session[:id])
    @sprite_arr = ["/assets/stopsign.png", "/assets/tree.png", "/assets/blank.png"]

    if @game.time <= 5
      @second_sprite = "/assets/bar.png"
    else
      @second_sprite = @sprite_arr.sample
    end

    gon.sprite_arr = @second_sprite

    if @game.time <= 0 || @game.fomo >= 100
      redirect_to game_end_index_path
    end

    @game = Game.find(session[:id])
    gon.username = @game.username
    gon.gametext = " "
    gon.fomo = @game.fomo
    gon.battery = @game.battery
    gon.time = @game.time
    gon.money = @game.money

  end

  def new
    @game = Game.new(params[:id])
    Event.all.each { |event| event.update_attributes(seen?: false) }
  end

  def create

    if params[:game][:occupation] == "Yoga Instructor"
      @game = Game.new(
        username: params[:game][:username],
        fomo: 50,
        battery: 45,
        money: 20,
        occupation: params[:game][:occupation],
        )
    elsif params[:game][:occupation] == "Hedge Fund Manager"
      @game = Game.new(
        username: params[:game][:username],
        fomo: 65,
        battery: 50,
        money: 40,
        occupation: params[:game][:occupation],
        )
    elsif params[:game][:occupation] == "Tech Bro"
      @game = Game.new(
        username: params[:game][:username],
        fomo: 65,
        battery: 70,
        money: 35,
        occupation: params[:game][:occupation],
        )
    end

    if @game.save
      session[:id] = @game.id
      @events = Event.all
      @events.each do |event|
        event.update_attributes(seen?: false)
      end
      redirect_to games_path
    else
      redirect_to new_game_path
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    redirect_to games_path
  end

end

app/views/games/index.html.erb
<div class="page-flexbox-wrapper">
  <div class="top-content">
    <div id="stats">
        <p> Name: <%= @game.username %> </p>
        <p> FOMO: <%= @game.fomo %>% <br> </p>
        <p> Time: <%= @game.time %> Minutes <br> </p>
        <p> Money: $<%= @game.money %> <br> </p>
        <p> Battery: <%= @game.battery %>% <br> </p>
    </div>
    <div id="event-header">
      <h1>Mission Trail</h1>
    </div>
    <div id="top-content-buffer"></div>
  </div>

<div class="sprite">
<img class="second_sprite" src=<%=@second_sprite%>
<br>
</div>
  <div class="all-options">
    <div class="options">
      <%= link_to "Hit the Trail", events_path %>
    </div>
    <div class="options">
    <% if @game.talked_to_locals == false %>
    <%= link_to "Talk to Locals", local_index_path %>
    <% end %>
    </div>
    <div class="options">
    <% if @game.checked_instagram == false && @game.battery > 0%>
    <%=  link_to "Check Instagram", instagram_index_path %>
    <% end %>
    </div>
    <div class="options">
    <% if @game.checked_tinder == false && @game.battery > 0 %>
    <%= link_to "Check Tinder", tinder_index_path %>
    <% end %>
    </div>
    <div class="options">
    <% if @game.checked_googlemaps == false && @game.battery > 0 %>
    <%= link_to "Check Google Maps", googlemaps_path %>
    <% end %>
    </div>
  </div>
</div>

app/views/games/new.html.erb
<div class="page-flexbox-wrapper">
  <div id="occupation-header">
    <h1>Choose a Career Path</h1>
  </div>
<div id="top-content-buffer"></div>
  <div class="occupation-container">
    <div class=occupations>
      <p id=job-title>Hedge Fund Manager:</p><p id=job-descriptor>The Ivy League-educated Hedge Fund Manager begins the game with the most money, highest level of FOMO and loves "The Wolf of Wall Street" for all the wrong reasons.</p>
      <p id=job-title>Tech Bro:</p><p id=job-descriptor>The valedictorian of his high school class, Tech Bro is an aspiring rapper and Tinder svengali. He begins the game with the most phone battery.</p>
      <p id=job-title>Yoga Instructor:</p><p id=job-descriptor>The Yoga Instructor begins the game with the least amount of money, but through constant mantras and sun salutations begins the game with the lowest level of FOMO.</p>
    </div>

  <%= form_for @game, url: {action: "create"}, :html => {:class => "create-game-form"} do |f| %>
  <div class="occupation-question">
    <p>What is your name?<p><%= f.text_field :username %>
    <br>
    <p>What is your occupation?<p><%= f.select :occupation, ['Hedge Fund Manager', 'Tech Bro', "Yoga Instructor"], { :class => 'selector-class' }%>
  </div>
  <div id="hit-trail">
    <%= f.submit "Let's Hit The Trail", :class => 'hit-trail-button' %>
    <% end %>
  </div>

app/views/games/show.html.erb
<% if @game.time == 0 %>
<%=  link_to "Enter Party", game_end_index_path %>

<% else %>

<h1>Welcome to the trail, <%=@game.username%></h1>

<h4>Fomo:</h4><%=@game.fomo %>
<h4>Minutes to goal:</h4><%=@game.time %>
<h4>Money:</h4>$<%=@game.money %>
<h4>Battery:</h4><%=@game.battery %>

<% end %>