config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :instagram, only: [:index, :show, :update]
  resources :tinder, only: [:index, :show, :update]
  resources :local, only: [:index, :show, :update]
  resources :attr_changes
  resources :googlemaps, only: [:index, :show, :update]
  resources :scoreboard, only: [:index, :new, :create]

  resources :events do
  resources :results

  end

  root to: 'welcome#index'

  resources :welcome, only: [:index, :show]
    get '/welcome/fomo_details', to: 'welcome#show'
    resources :game_end, only: [:index]
end

app/controllers/local_controller.rb
class LocalController < ApplicationController
 include ApplicationHelper

  def index
    @game = Game.find(session[:id])
    @game.update_attributes(talked_to_locals: true)
    @event_array = Event.local.where(seen?: false)
    if @event_array.empty?
      Event.reset_locals
      @event_array = Event.local
    end
    @event = @event_array.sample
    @event.update_attributes(seen?: true)
    redirect_to local_path(@event)
  end

  def show
    @game = Game.find(session[:id])
    @event = Event.find(params[:id])
  end

  def update

  end
end

app/views/local/index.html.erb
<div class="event-flexbox-wrapper">
  <div class="top-content">
    <div id="stats">
      <p> Name: <%= @game.username %> </p>
      <p> FOMO: <%= @game.fomo %>% <br> </p>
      <p> Time: <%= @game.time %> Minutes <br> </p>
      <p> Money: $<%= @game.money %> <br> </p>
      <p> Battery: <%= @game.battery %>% <br> </p>
    </div>
    <div id="event-header">
      <h1>Local Wisdom</h1>
    </div>
    <div id="top-content-buffer"></div>
  </div>
</div>
  <div class="options">
        <%=@event.text%>
  </div>
  <div class="flexbox-event-content">
  <div class="image">
    <img src=<%=@event.image_url%>>
  </div>
  <div id="event-content-buffer"></div>
      <div class="trail-return-link"><%= link_to "Return to Trail", attr_change_path(@attr_change), method: "put"%>
      </div>
  </div>
</div>

app/views/local/show.html.erb
<div class="event-flexbox-wrapper">
  <div class="top-content">
    <div id="stats">
      <p> Name: <%= @game.username %> </p>
      <p> FOMO: <%= @game.fomo %>% <br> </p>
      <p> Time: <%= @game.time %> Minutes <br> </p>
      <p> Money: $<%= @game.money %> <br> </p>
      <p> Battery: <%= @game.battery %>% <br> </p>
    </div>
    <div id="event-header">
      <h1>Local Wisdom</h1>
    </div>
    <div id="top-content-buffer"></div>
  </div>
</div>
  <div class="options">
        <%=@event.text%>
  </div>
  <div class="flexbox-event-content">
  <div class="image">
    <img src=<%=@event.image_url%>>
  </div>
  <div id="event-content-buffer"></div>
      <div class="trail-return-link"><%= link_to "Return to Trail", attr_change_path(@event.attr_change), method: "put"%>
      </div>
  </div>
</div>